### ISSUE TITLE
Check line 48 of MLG.xml

### ISSUE THREAD

**Issue by Willster419** [Aimdrol/MLG-Main#1]
I think you have an accidental typing error:
`<stayTime>5.0></stayTime> <!-- How long the Elements stay, use a FLOAT HERE (Komma) -->`
extra > at 5.0**>**

**Comment by Aimdrol** [comment]
Indeed. Thanks for bringing it to my attention.
This has been fixed with 5eec18cdf560e30de2829563469fa2baf31d7493
