### ISSUE TITLE
Updates needed for 1.10.1.0

### ISSUE THREAD

**Issue by Willster419** [Aimdrol/MLG-Main#10]
- The wwise sound banks need updates
- Localization needs to be updated
  - I encourage you to look into a mod that does specific text string replacements for you so you don't need to re-do this every localization update.
- Haven't tested scripts yet

I additionally encourage you to put the project source under source control so people can contribute and provide updates

**Comment by Aimdrol** [comment]
Updated localization files and the sound banks. Intial tests look good so far!

**Comment by Willster419** [comment]
guiControlsLobbyBattle.swf has not been updated and causes the players panel to not appear in the battle


what does this file do? does it provide text or images?

**Comment by Aimdrol** [comment]
It's actually not used at all and has been deleted with f5e183ced657348c7eec9f45e12a18439756b0cd

**Comment by Willster419** [comment]
i see, thanks!
