### ISSUE TITLE
MoE Italian names are incorrect

### ISSUE THREAD

**Issue by Willster419** [Aimdrol/MLG-Main#2]
you have the names with "italy", but looking at the gui package for WoT 1.0.2.1, the name is "italian"
https://puu.sh/AGZsF/08df76aa0a.png

**Comment by Aimdrol** [comment]
Thanks for bringing this to my attention. It was fixed with d805ac849b1491f4a3b802ea3f46c3c4a91c7db8

I don't get why WG is using italian instead of italy there but ¯\\_(ツ)_/¯
