### ISSUE TITLE
1.1.0 Issues

### ISSUE THREAD

**Issue by Willster419** [Aimdrol/MLG-Main#4]
Hi Aimdrol!
With the 1.1.0 update, WG has changed the version of wwise they are using, and all sound mods need to be updated.
I recommend that you download the latest project from koreanrandom, and move your files into there.
As for the scripts, they all seem to work and are not affected.
The translation (*.mo) files will need to be updated.

As a recommendation, I would look into a method of making a script to automatically replace the translated strings with the text you want, rather than manually having to re-create the mo files with every update.
I know KRZYSZTOF CHODAK had a mod for a while called "tidy messenger" that did this, and i think some of the stats mods like YasenCrasen do this as well.

Love your mods, been using them since 8.5!

**Comment by Aimdrol** [comment]
Hey, thanks again for the feedback :)

The soundbanks were updated with 2f6eb64fb5628765c57213f4f0a9da847eda2912
Localization files were updated with 6195498f6062afe91ac676f093395e4f4047e194 and 8e71a300800c3f7ea52895c9b32bf28a70f7852b

Once I find the time I'll check the dynamic string replacing you've mentioned
