### ISSUE TITLE
Question about the sound banks

### ISSUE THREAD

**Issue by Willster419** [Aimdrol/MLG-Main#5]
Hey,
Would it be possible if you could separate the MLG.bnk into groups? For example:
Sixth sense could have its own bnk
Hitmarker could have its own bnk
and others...

Reason being that many modpacks separate your mod out into parts, so users only install specific parts of your mod as they want them. I can't speak for all modpacks, but we separate your mod into the foll wing groups:
-Consumables
-Hitmarker
-Loading Video
-MoE
-RTAN
-Crew sounds
-6th sense selection

Again, I can't speak for all modpacks, but we (the modpack team) would appreciate it if you could separate the sound banks based on the above defined groups. That way, when a user is selecting mods in our modpack, they are only downloading the sound files they need, rather than a 14MB file for all sounds.
If you can't feasibly do it, don't worry about it, it's no big deal.
 Thanks for maintaining the mod!

**Comment by Aimdrol** [comment]
Is there an easier way to load sound banks than by editing engine_config.xml?
When the sound bank is separated into multiple ones, the installer would have to edit engine_config.xml depending on the selected parts.

**Comment by Willster419** [comment]
have you not used audio_mods.xml? 

[audio_mods.txt](https://github.com/Aimdrol/MLG-Main/files/2574497/audio_mods.txt)

Rename to audio_mods.xml.

you put the file in in res_mods/versiondir/audioww/audio_mods.xml
you can specify banks, RTPC, even redirect events! It's much easier to use then having to parse engine_config.xml

**Comment by Aimdrol** [comment]
No, I'll check it. Though the xml editing part depending on the selected parts still has to be done.

**Comment by Willster419** [comment]
I'm not sure how your setup (i assume inno setup) works for manual file editing, but you could do a find and replace, something like:
search for "`<loadBanks>`"
replace with "`<loadBanks>`" + "`\r\n`" + `[spaces]` + `<bank>MLG.bnk</bank>`

the order of which the banks are loaded is first to last, but should not matter if your sound events don't overlap.
