### ISSUE TITLE
Exit game menu not showing with Ingame consumables

### ISSUE THREAD

**Issue by Willster419** [Aimdrol/MLG-Main#6]
Hey (again, sorry for multiple issues in a day)
I just found that the "exit game" menu is broken when the MLG consumables are installed:
https://puu.sh/BWk2r/f658a21577.png

This can be replicated in the following:
Install the "main" part of the MLG mod. (Specifically, the file guiControlsLobbyBattle.swf)
log into the game
menu->exit game.
the broken screen will appear.

**Comment by Aimdrol** [comment]
I just tested it and the menu works fine for me.

**Comment by Willster419** [comment]
I did a client repair and cleared cache, it seems to have gone away. I knew for sure it was that file, but a cache clearing seems to have solved the issue. Interesting.

NVM then.
