### ISSUE TITLE
cannot open ElementsFile

### ISSUE THREAD

**Issue by Yamahou** [Aimdrol/MLG-Main#8]
![World of Tanks Screenshot 2020 01 20 - 19 19 13 69](https://user-images.githubusercontent.com/60098416/72726182-4a04b600-3bba-11ea-849c-f2c0696f3e02.png)
Hi how can i fix this?

**Comment by Aimdrol** [comment]
Fixed with cddaff6a600c3bb34cc35613f8efeb921af93912
